#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# Use alt as the modifier to resize/move windows with the mouse
bspc config pointer_modifier mod1

bspc rule -a Zathura state=tiled

wmname compiz

$XDG_CONFIG_HOME/polybar/launch.sh &

pgrep bspswallow || bspswallow &

